FROM python:3.8-alpine

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash git vim sudo

RUN addgroup -g 1000 developers
RUN addgroup root developers
RUN adduser -D -u 1000 -s /bin/bash -h /home/vduser -G developers vduser
RUN echo '%developers ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

COPY config/.* /home/vduser
RUN chown vduser:developers /home/vduser/.*
RUN mkdir -p /home/vduser/visidata \
  && chown vduser:developers /home/vduser/visidata

USER vduser
WORKDIR /home/vduser

RUN pip install requests python-dateutil wcwidth
